version: '2.4'
services:
  alpine:
    image: ghcr.io/dadevel/alpine:testing
    cap_drop:
    - all
    tty: yes

  aria2:
    image: ghcr.io/dadevel/aria2:testing
    cap_drop:
    - all

  bitcoind:
    image: ghcr.io/dadevel/bitcoind:testing
    cap_drop:
    - all

  blackarch:
    image: ghcr.io/dadevel/blackarch:testing
    cap_drop:
    - all
    cap_add:
    - setgid
    - setuid
    tty: yes

  busybox:
    image: ghcr.io/dadevel/busybox:testing
    cap_drop:
    - all
    tty: yes

  cxx-builder:
    image: ghcr.io/dadevel/cxx-builder:testing
    cap_drop:
    - all
    tty: yes

  cadvisor:
    image: ghcr.io/dadevel/cadvisor:testing
    privileged: true
    userns_mode: host
    pid: host
    devices:
    - /dev/kmsg
    volumes:
    - /:/rootfs:ro
    - /dev/disk:/dev/disk:ro
    - /etc/machine-id:/etc/machine-id:ro
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
    - /var/run:/var/run:ro

  chrony:
    image: ghcr.io/dadevel/chrony:testing
    entrypoint: [/bin/sh, -c]
    command: ['chronyd --version && sleep 3']
    healthcheck:
      test: [NONE]
    cap_drop:
    - all
    cap_add:
    - net_bind_service
    - sys_time
    volumes:
    - /etc/adjtime:/app/config/adjtime:ro

  debian:
    image: ghcr.io/dadevel/debian:testing
    cap_drop:
    - all
    tty: yes

  go-builder:
    image: ghcr.io/dadevel/go-builder:testing
    cap_drop:
    - all
    tty: yes

  grafana:
    image: ghcr.io/dadevel/grafana:testing
    cap_drop:
    - all

  haveged:
    image: ghcr.io/dadevel/haveged:testing
    cap_drop:
    - all
    cap_add:
    - sys_admin

  hostapd:
    image: ghcr.io/dadevel/hostapd:testing
    entrypoint: [/bin/sh, -c]
    command: ['hostapd -v || true && sleep 3']
    healthcheck:
      test: [NONE]
    cap_drop:
    - all
    cap_add:
    - net_admin
    - net_raw
    - sys_rawio
    devices:
    - /dev/rfkill

  lego:
    image: ghcr.io/dadevel/lego:testing
    entrypoint: [/bin/sh, -c]
    command: [lego --version && touch /dev/shm/healthy && sleep 3]
    cap_drop:
    - all

  nginx:
    image: ghcr.io/dadevel/nginx:testing
    cap_drop:
    - all
    cap_add:
    - net_bind_service

  nodejs-builder:
    image: ghcr.io/dadevel/nodejs-builder:testing
    cap_drop:
    - all
    tty: yes

  prometheus:
    image: ghcr.io/dadevel/prometheus:testing
    cap_drop:
    - all

  prometheus-alertmanager:
    image: ghcr.io/dadevel/prometheus-alertmanager:testing
    cap_drop:
    - all

  prometheus-apt-collector:
    image: ghcr.io/dadevel/prometheus-apt-collector:testing
    cap_drop:
    - all
    volumes:
    - /etc/apt:/rootfs/etc/apt:ro
    - /etc/dpkg:/rootfs/etc/dpkg:ro
    - /run:/rootfs/run:ro
    - /usr/share/dpkg:/rootfs/usr/share/dpkg:ro
    - /var/lib/apt:/rootfs/var/lib/apt:ro
    - /var/lib/dpkg:/rootfs/var/lib/dpkg:ro

  prometheus-blackbox-exporter:
    image: ghcr.io/dadevel/prometheus-blackbox-exporter:testing
    cap_drop:
    - all
    sysctls:
      net.ipv4.ping_group_range: 0 1000

  prometheus-nftables-exporter:
    image: ghcr.io/dadevel/prometheus-nftables-exporter:testing
    network_mode: host
    cap_drop:
    - all
    cap_add:
    - net_admin

  prometheus-node-exporter:
    image: ghcr.io/dadevel/prometheus-node-exporter:testing
    network_mode: host
    userns_mode: host
    pid: host
    cap_drop:
    - all
    volumes:
    - /:/rootfs:ro,rslave
    # systemd collector doesn't respect --path.rootfs
    - /var/run:/var/run:ro

  prometheus-signal-receiver:
    image: ghcr.io/dadevel/prometheus-signal-receiver:testing
    entrypoint: [/bin/sleep, '3']
    healthcheck:
      test: [NONE]
    cap_drop:
    - all

  prometheus-smart-collector:
    image: ghcr.io/dadevel/prometheus-smart-collector:testing
    entrypoint: [/bin/sh, -c]
    command: [touch /dev/shm/healthy && sleep 3]
    cap_drop:
    - all
    cap_add:
    - sys_rawio
    devices:
    - /dev/sda

  python3:
    image: ghcr.io/dadevel/python3:testing
    cap_drop:
    - all
    tty: yes

  signal-cli:
    image: ghcr.io/dadevel/signal-cli:testing
    command: --version
    cap_drop:
    - all
    tmpfs:
    # java insists in writing a shared library to /tmp and loading it later
    - /tmp:rw,nodev,nosuid,exec,mode=1770

  stdiscosrv:
    image: ghcr.io/dadevel/stdiscosrv:testing
    cap_drop:
    - all

  strelaysrv:
    image: ghcr.io/dadevel/strelaysrv:testing
    cap_drop:
    - all

  syncthing:
    image: ghcr.io/dadevel/syncthing:testing
    network_mode: host
    cap_drop:
    - all

  unbound:
    image: ghcr.io/dadevel/unbound:testing
    cap_drop:
    - all
    cap_add:
    - net_bind_service

  watchtower:
    image: ghcr.io/dadevel/watchtower:testing
    command: --label-enable
    cap_drop:
    - all
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

  webui-aria2:
    image: ghcr.io/dadevel/webui-aria2:testing
    cap_drop:
    - all

  wpa-supplicant:
    image: ghcr.io/dadevel/wpa-supplicant:testing
    entrypoint: [/bin/sh, -c]
    command: ['wpa_supplicant -v && sleep 3']
    healthcheck:
      test: [NONE]
    cap_drop:
    - all
    cap_add:
    - net_admin
    - net_raw
    - sys_rawio
    devices:
    - /dev/rfkill

